### PR TITLE
I would appreciate it if this project shows some more comformance with the standard

### PR DESCRIPTION
**Pull request by brynne8**
I don't understand why the implicit type casts are not implemented, which prevents some features from working. And "T& const" expression cannot be parsed. 
Another problem. When I used my Visual Studio 2008 Service Pack 2 to compile the project, some tests failed(i.e, ../verify/except1.cpp), so I re-compile it with VC6 and the exception is caught. I am wondering where did the iostrm.cpp and iostrm.h go.
Inside math.h

``` cpp
#ifndef __MATH_H
#define __MATH_H
#lib libm.so
extern "C" {
/* From Appendix B4 of K&R2 */
```

If I use ucc.exe in windows, libm.so will not be found, why remove the following

``` cpp
#ifdef __win32__
#lib msvcrt40.dll
#else
#lib libm.so
#endif
```

The idea to interpret C++ like using scripting languages is very new to me. And why not maintain this project and build up-to-date binaries for beginners~ I am willing to commit some minor changes, huh~

Linenoise updated, on http://github.com/antirez/linenoise 
But how can Microsoft Visual C++ compile the linenoise?

### CODE REVIEW

**Comment by brynne8** [comment]
Oh god. You used standard iostream instead of former iostrm aliases. 
A linenoise windows version is on https://code.google.com/p/dart-console/source/browse/linenoise.c

**Comment by stevedonovan** [comment]
You're right - math.h needs to link to mscrt.  I haven't tried compiling with VC (post VC6) since I don't have a 32-bit Windows machine anymore.  As for linenoise, it's mostly not needed on Windows since the console does history and line editing for us anyway - you'd only need it if you wanted tab completion.

iostrm.h was a hack I used when the standard library wasn't so well supported in VC and I wanted faster compile times (ditto for the non-standard string class).

I think the 'downloads' page mentioned in the readme has gone - I'll provide links to Linux x86 and MinGW Windows binaries (which doesn't need the VC runtiime)

To be honest, I am embarrassed by some of the code in this project - there is far too much 'char_' where 'const char_' is needed. The bison grammar is a mess with lots of lexical tie-ins, and we depend on x86 assembler to call external C functions. I'd like to move towards using libffi, and then the 32-bit restriction can be removed.  Any attempt to consume C++ DLLs directly will have to be abandoned, since the ABI is complicated and has been changing all the time. (C is easy; that's what libffi does well)  I'd love to implement some C++11 features like extended for-statement and lambdas, but this is tricky.  I realized that C++ is too big a language to be implemented properly by a single person!

I'll look at "T& const" (idiom is to say "const T&"?)

Which 'implicit type casts' are you thinking of?

Thanks for your interest in the project.  The idea was that people could learn the language in an interactive way, or an experienced user could explore using new libraries, and so forth.

**Comment by brynne8** [comment]
Well, my 'implicit type casts' just refers to this kind of code

``` cpp
// make_pair example
#include <utility>      // std::pair
#include <iostream>     // std::cout

int main () {
  std::pair <int,int> foo;
  std::pair <int,int> bar;

  foo = std::make_pair (10,20);
  bar = std::make_pair (10.5,'A'); // ok: implicit conversion from pair<double,char>

  std::cout << "foo: " << foo.first << ", " << foo.second << '\n';
  std::cout << "bar: " << bar.first << ", " << bar.second << '\n';

  return 0;
}
```

This kind of cast is allowed for std::pair <int,int> bar;

Well, I think you have implemented a fairly large subset of the C++ language. There is another interpreter I found before I've found your UnderC interpreter called Ch interpreter, but it even cannot parse classes without a keyword "class":

``` cpp
class A
{
   class B
   {
      B * somebee; //error
   }
};
```

Interactive is a 'big" highlight and I may use your interpreter to help some of my friends who are not so familiar with C++ grammar. I downloaded a ebook copy of your C++ by Examples and have read some chapters ;-). It's really a different approach to the Learning of the language. 
Anyway, your source code helped me understand the mechanisms of the compiler, 'cause I would have been confronted with a large quantity of code if I read the source of OpenWatcom C++ or GCC~~~ Thanks.

**Comment by stevedonovan** [comment]
Ah, I see - `std::pair` defines template assignment operator:

```
   template<class _U1 , class _U2 > pair & operator= (const pair< _U1, _U2 > &__p) 
```

(see http://gcc.gnu.org/onlinedocs/gcc-4.7.0/libstdc++/api/a00444.html)

Let me look at the template method problem....

You will be interested to know that 'except1.cpp' blows up here on Linux Mint ;) So the problem is not just MSVC.

Glad you like the learning approach - that was exactly the idea.  It allows a person to learn the language in a conversational way, and not get distracted by errors and long compile times.

**Comment by stevedonovan** [comment]
Problem in `except1.cpp` is with UnderC extension to catch integer overflow.  Not portable to standard C++ (but still useful for testing?)

http://www.cplusplus.com/forum/general/58117/

**Comment by brynne8** [comment]
I need explanation. This is a simple program with classes. 

``` cpp
class CelestialBody
{
public:
    CelestialBody(double mass)
        :_mass(mass)
    {}
private:
    const double _mass;
};

class Star: public CelestialBody //Star is a CelestialBody
{
public:
    Star(double mass, double brightness)
        :CelestialBody(mass), _brightness(brightness)
    {}
private:
    const double _brightness;
};

class BlackHole
{
public:
    void Gobble(CelestialBody * pBody);
};

void BlackHole::Gobble(CelestialBody * pBody)
{
    delete pBody;
}
BlackHole TheBlackHole;

int main()
{
    Star aStar(1234.5, 0.1);
    Star* pStar = new Star(1, 2);
    TheBlackHole.Gobble(pStar);
    return 0;
}
```

ucc.exe has a warning --- (20): cannot access '='
But it runs well. Does this warning matters? Can we just disable it by #opt a+?

**Comment by stevedonovan** [comment]
Thanks for the PR, Alexander.  I will track down this one - looks like the generated '=' operator for this class wasn't accessible for some reason. However, at least it's not currently an error!

A more serious issue is that operators like '<' are not working for std:pair, at least for me. 

I'm looking at improving C99 support, in particular variadic macros.  That may seem like an odd priority, but I do a lot of C at the moment ;)

**Comment by brynne8** [comment]
It seems that friend class will cause a parsing error. 

``` cpp
class A
{
  friend class B;
}
//and
class B;
class A
{
  friend class B;
}
```

Recursive use of template function is not okay.

``` cpp
template<class BI1, class BI2>
  BI2 copy_backward(BI1 i1, BI1 i2, BI2 j)
  {
    while (i1 != i2)
      *(--j) = *(--i2);
    return j;
  }
```

After adding the copy_backward method to <algorithm> header, the quick sort could be:

``` cpp
//Code is simplified from P J Plauger's version
#include <iostream>
#include <algorithm>

template<class Ty> inline
Ty median(Ty a, Ty b, Ty c)
{
    if (a < b)
        return (b < c ? b : a < c ? c : a);
    else
        return (a < c ? a : b < c ? c : b);
}

const int SORT_MAX = 16;

template<class It> inline
void sort(It i1, It i2)
{
    if (i2 - i1 <= SORT_MAX)
        insertion_sort(i1, i2);
    else
    {
        sort_helper(i1, i2);
        insertion_sort(i1, i1 + SORT_MAX);
        for (i1 += SORT_MAX; i1 != i2; ++i1)
            unguarded_insert(i1, *i1);
    }
}

template<class It> inline
void sort_helper(It i1, It i2)
{
    for (; SORT_MAX< i2 - i1; )
    {
        It mid = unguarded_partition(i1, i2,
            median(*i1, *(i1 + (i2 - i1) / 2), *(i2 - 1)));
        if (i2 - mid <= mid - i1)
        {
            sort_helper<It>(mid, i2);
            i2 = mid;
        }
        else
        {
            sort_helper<It>(i1, mid);
            i1 = mid;
        }
    }
}

template<class It, class T> inline
It unguarded_partition(It i1, It i2, T pivot)
{
    for (; ; ++i1)
    {
        for (; *i1 < pivot; ++i1);
        for (; pivot < *(--i2); );
        if (i2 < i1)
            return i1;
        std::swap(*i1, *i2);
    }
}

template<class BI> inline
void insertion_sort(BI i1, BI i2)
{
    if (i1 == i2) return;
    for (BI mid = i1; ++mid != i2; )
    {
        decltype(*i1) v = *mid;
        if (!(v < *i1))
            unguarded_insert(mid, v);
        else
        {
            std::copy_backward(i1, mid, mid + 1);
            *i1 = v;
        }
    }
}

template<class BI, class T> inline
void unguarded_insert(BI i2, T v)
{
    for (BI mid = i2; v < *(--mid); i2 = mid)
        *i2 = *mid;
    *i2 = v;
}

int main()
{
    int a[] = {1,2,4,3,5,7,0,2,6,4,33,765,345,234,252,23,64,34,54,6,5,3,645,254,234,5,23,25,422,432};
    sort(a, a+30);
    for (int i = 0; i < 30; ++i)
        std::cout << *(a+i) << " ";
}
```

I tried to run this quicksort but the template function sort_helper can't do the recursion. 
Additionally, just like "T const &", "T const *" should be parsed, as char const \* should be treated the same as "const char *". I tried operator overloading with two variables, seeing you had implemented std::string in a complied static library.

**Pull request merged**
